<a href="https://colab.research.google.com/github/raamiiChu/NCCU_111-1_DCT_Blockchain-Application-Development_Final-Project/blob/main/%E7%A8%8B%E5%BC%8F%E7%A2%BC_%E6%8A%93%E5%8F%96%20gas%20fee/gas_fee.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 下載 selenium

In [ ]:
!apt-get update
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin
!pip install selenium

Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease
Get:3 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]
Get:4 http://deb.debian.org/debian-security buster/updates InRelease [34.8 kB]
Hit:5 https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/ InRelease
Ign:6 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu2004/x86_64  InRelease
Hit:7 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:8 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease
Hit:9 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu2004/x86_64  Release
Hit:10 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu focal InRelease
Hit:11 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:12 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Get:13 http://deb.debian.org/debian buster/main amd64 Packages [10.7 MB]
Hit:14 http://ppa.launchpad.net/cran/libgit2/ubuntu focal InRelease
Get:15 http://deb.debian.org/debian buster-updates/main amd64 Packages [9,745 B]
Hit:16 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease
Hit:17 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu focal InRelease
Get:18 http://deb.debian.org/debian-security buster/updates/main amd64 Packages [547 kB]
Hit:19 http://ppa.launchpad.net/saiarcot895/chromium-beta/ubuntu focal InRelease
Fetched 11.5 MB in 4s (3,171 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
chromium-chromedriver is already the newest version (1:108.0.5359.40-0ubuntu1~ppa1~20.04.1).
The following packages were automatically installed and are no longer required:
  apparmor liblzo2-2 libnvidia-common-510 snapd squashfs-tools
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 34 not upgraded.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: selenium in /usr/local/lib/python3.8/dist-packages (4.8.0)
Requirement already satisfied: urllib3[socks]~=1.26 in /usr/local/lib/python3.8/dist-packages (from selenium) (1.26.14)
Requirement already satisfied: trio~=0.17 in /usr/local/lib/python3.8/dist-packages (from selenium) (0.22.0)
Requirement already satisfied: certifi>=2021.10.8 in /usr/local/lib/python3.8/dist-packages (from selenium) (2022.12.7)
Requirement already satisfied: trio-websocket~=0.9 in /usr/local/lib/python3.8/dist-packages (from selenium) (0.9.2)
Requirement already satisfied: async-generator>=1.9 in /usr/local/lib/python3.8/dist-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.8/dist-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in /usr/local/lib/python3.8/dist-packages (from trio~=0.17->selenium) (2.10)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.8/dist-packages (from trio~=0.17->selenium) (22.2.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.8/dist-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: outcome in /usr/local/lib/python3.8/dist-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in /usr/local/lib/python3.8/dist-packages (from trio~=0.17->selenium) (1.1.0)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.8/dist-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.8/dist-packages (from urllib3[socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /usr/local/lib/python3.8/dist-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [ ]:
%%shell
# Ubuntu no longer distributes chromium-browser outside of snap
#
# Proposed solution: https://askubuntu.com/questions/1204571/how-to-install-chromium-without-snap

# Add debian buster
cat > /etc/apt/sources.list.d/debian.list <<'EOF'
deb [arch=amd64 signed-by=/usr/share/keyrings/debian-buster.gpg] http://deb.debian.org/debian buster main
deb [arch=amd64 signed-by=/usr/share/keyrings/debian-buster-updates.gpg] http://deb.debian.org/debian buster-updates main
deb [arch=amd64 signed-by=/usr/share/keyrings/debian-security-buster.gpg] http://deb.debian.org/debian-security buster/updates main
EOF

# Add keys
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys DCC9EFBF77E11517
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 112695A0E562B32A

apt-key export 77E11517 | gpg --dearmour -o /usr/share/keyrings/debian-buster.gpg
apt-key export 22F3D138 | gpg --dearmour -o /usr/share/keyrings/debian-buster-updates.gpg
apt-key export E562B32A | gpg --dearmour -o /usr/share/keyrings/debian-security-buster.gpg

# Prefer debian repo for chromium* packages only
# Note the double-blank lines between entries
cat > /etc/apt/preferences.d/chromium.pref << 'EOF'
Package: *
Pin: release a=eoan
Pin-Priority: 500


Package: *
Pin: origin "deb.debian.org"
Pin-Priority: 300


Package: chromium*
Pin: origin "deb.debian.org"
Pin-Priority: 700
EOF

Executing: /tmp/apt-key-gpghome.3iSlId4ioZ/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys DCC9EFBF77E11517
gpg: key DCC9EFBF77E11517: "Debian Stable Release Key (10/buster) <debian-release@lists.debian.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Executing: /tmp/apt-key-gpghome.AVGqUxeh4S/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
gpg: key DC30D7C23CBBABEE: "Debian Archive Automatic Signing Key (10/buster) <ftpmaster@debian.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Executing: /tmp/apt-key-gpghome.MdWhUSHHB4/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 112695A0E562B32A
gpg: key 4DFAB270CAA96DFA: "Debian Security Archive Automatic Signing Key (10/buster) <ftpmaster@debian.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
gpg: cannot open '/dev/tty': No such device or address
Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: [stdout]: write error: Broken pipe
gpg: filter_flush failed on close: Broken pipe
gpg: cannot open '/dev/tty': No such device or address
Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: [stdout]: write error: Broken pipe
gpg: filter_flush failed on close: Broken pipe
gpg: cannot open '/dev/tty': No such device or address
Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: [stdout]: write error: Broken pipe
gpg: filter_flush failed on close: Broken pipe

### 下載模組、設定瀏覽器

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from selenium import webdriver
from selenium.webdriver.common.by import By

options = webdriver.ChromeOptions()
options.add_argument('--headless')
options.add_argument('--no-sandbox')
options.add_argument('--disable-dev-shm-usage')
driver = webdriver.Chrome('chromedriver',options=options)
driver.implicitly_wait(10)

### 讀取資料

In [ ]:
!dir *.csv

The\ Binding\ String.csv  The\ Spectrum\ Of\ Nature.csv

In [ ]:
file_name = "The Spectrum Of Nature"

file_path = f"/content/{file_name}.csv"
fxhash_data = pd.read_csv(file_path, encoding="utf-8")

##### 預覽資料

In [ ]:
fxhash_data

,name,minter,generationHash,listings,offers
0,The Spectrum Of Nature #271,"{""name"":""culla"",""id"":""tz1gE27FWHXzisp1SgkuupZ4...",oo2L6pGGBthqPwMSctb2op2YLUyK1gQ2dc4AiSpHM8tLie...,[],[]
1,The Spectrum Of Nature #270,"{""name"":""fleep"",""id"":""tz1LB8GK5E9wUgTqSRaJKHqK...",ooanMZ7QcpuNraXr7AegS5nKL1GuX6xbmZU94T3KKsqyf1...,"[{""price"":1800000000,""acceptedAt"":null}]",[]
2,The Spectrum Of Nature #269,"{""name"":""MarkLudgatex"",""id"":""tz1PvJ24Uj4CPfrDL...",onoccWpTvLHUpqoy9z6EchRzt67688EDF5K1ctPi5A7xWh...,"[{""price"":315000000,""acceptedAt"":null},{""price...","[{""price"":120000000,""acceptedAt"":""2022-12-25T2..."
3,The Spectrum Of Nature #268,"{""name"":""MarkLudgatex"",""id"":""tz1PvJ24Uj4CPfrDL...",ooAExYKWamZokUvUzwZzNUG6jvt1wpdkFgu9UZFs6jjxjJ...,[],[]
4,The Spectrum Of Nature #267,"{""name"":""MarkLudgatex"",""id"":""tz1PvJ24Uj4CPfrDL...",oohrqGUqHqJ2WdWroCcT1tPTL5d7r4qu5uZ2KtT9sfnLK2...,[],"[{""price"":50000000,""acceptedAt"":null}]"
...,...,...,...,...,...
266,The Spectrum Of Nature #5,"{""name"":""guiboguibo"",""id"":""tz1TFjv1rC41koxYBVc...",onnZokNwyaUG8czTNTZmNpSvRYnHyYFdKa8ddDf9AuDt9z...,"[{""price"":444000000,""acceptedAt"":null},{""price...",[]
267,The Spectrum Of Nature #4,"{""name"":""saiyajin"",""id"":""tz1NC1gVtqD7TBqeoSr6H...",ooZromen7RhvwQCViJAkdTPmCxxfc9Vu8km62FqM1HuX5N...,"[{""price"":355000000,""acceptedAt"":null},{""price...",[]
268,The Spectrum Of Nature #3,"{""name"":""Astronaut"",""id"":""tz1fwGb9vHQARr63Tiur...",op1658BqHYVNZnNk642y6M11vkWsFiqvDQHZyZUPCzKCoT...,"[{""price"":360000000,""acceptedAt"":null},{""price...",[]
269,The Spectrum Of Nature #2,"{""name"":""Elessar"",""id"":""tz1N1mMncpToi74HPsR6qi...",op4XTzuoJrB8R2xNZ3ZWiw79VpBMpU75yFZe6XPACYRB2N...,"[{""price"":380000000,""acceptedAt"":null},{""price...","[{""price"":125000000,""acceptedAt"":null}]"
270,The Spectrum Of Nature #1,"{""name"":""Majus"",""id"":""tz1auz1pxbirGzwkLvHXrhsq...",opDUBhBEmRcdd327sBa15ZPfFymW14w2vAckRGQ12De6o4...,"[{""price"":199000000,""acceptedAt"":""2022-11-30T2...",[]

### 爬取 gas fee

In [ ]:
generationHash = fxhash_data["generationHash"]
gas_fees = []

for hash in generationHash:
    url = f"https://tzkt.io/{hash}"
    
    driver.get(url)

    gas_fee = driver.find_element(By.CLASS_NAME, "text-right")

    gas_fees.append(float(gas_fee.text[:-1]))

driver.quit()

In [ ]:
fxhash_data["gas_fee"] = gas_fees

##### 預覽資料

In [ ]:
fxhash_data

,name,minter,generationHash,listings,offers,gas_fee
0,The Spectrum Of Nature #271,"{""name"":""culla"",""id"":""tz1gE27FWHXzisp1SgkuupZ4...",oo2L6pGGBthqPwMSctb2op2YLUyK1gQ2dc4AiSpHM8tLie...,[],[],0.003975
1,The Spectrum Of Nature #270,"{""name"":""fleep"",""id"":""tz1LB8GK5E9wUgTqSRaJKHqK...",ooanMZ7QcpuNraXr7AegS5nKL1GuX6xbmZU94T3KKsqyf1...,"[{""price"":1800000000,""acceptedAt"":null}]",[],0.003860
2,The Spectrum Of Nature #269,"{""name"":""MarkLudgatex"",""id"":""tz1PvJ24Uj4CPfrDL...",onoccWpTvLHUpqoy9z6EchRzt67688EDF5K1ctPi5A7xWh...,"[{""price"":315000000,""acceptedAt"":null},{""price...","[{""price"":120000000,""acceptedAt"":""2022-12-25T2...",0.003975
3,The Spectrum Of Nature #268,"{""name"":""MarkLudgatex"",""id"":""tz1PvJ24Uj4CPfrDL...",ooAExYKWamZokUvUzwZzNUG6jvt1wpdkFgu9UZFs6jjxjJ...,[],[],0.003975
4,The Spectrum Of Nature #267,"{""name"":""MarkLudgatex"",""id"":""tz1PvJ24Uj4CPfrDL...",oohrqGUqHqJ2WdWroCcT1tPTL5d7r4qu5uZ2KtT9sfnLK2...,[],"[{""price"":50000000,""acceptedAt"":null}]",0.003975
...,...,...,...,...,...,...
266,The Spectrum Of Nature #5,"{""name"":""guiboguibo"",""id"":""tz1TFjv1rC41koxYBVc...",onnZokNwyaUG8czTNTZmNpSvRYnHyYFdKa8ddDf9AuDt9z...,"[{""price"":444000000,""acceptedAt"":null},{""price...",[],21.480000
267,The Spectrum Of Nature #4,"{""name"":""saiyajin"",""id"":""tz1NC1gVtqD7TBqeoSr6H...",ooZromen7RhvwQCViJAkdTPmCxxfc9Vu8km62FqM1HuX5N...,"[{""price"":355000000,""acceptedAt"":null},{""price...",[],21.480000
268,The Spectrum Of Nature #3,"{""name"":""Astronaut"",""id"":""tz1fwGb9vHQARr63Tiur...",op1658BqHYVNZnNk642y6M11vkWsFiqvDQHZyZUPCzKCoT...,"[{""price"":360000000,""acceptedAt"":null},{""price...",[],21.000000
269,The Spectrum Of Nature #2,"{""name"":""Elessar"",""id"":""tz1N1mMncpToi74HPsR6qi...",op4XTzuoJrB8R2xNZ3ZWiw79VpBMpU75yFZe6XPACYRB2N...,"[{""price"":380000000,""acceptedAt"":null},{""price...","[{""price"":125000000,""acceptedAt"":null}]",22.000000
270,The Spectrum Of Nature #1,"{""name"":""Majus"",""id"":""tz1auz1pxbirGzwkLvHXrhsq...",opDUBhBEmRcdd327sBa15ZPfFymW14w2vAckRGQ12De6o4...,"[{""price"":199000000,""acceptedAt"":""2022-11-30T2...",[],25.500000

In [ ]:
gas_fee = fxhash_data["gas_fee"]
sum(gas_fee) / len(gas_fee)

14.197690073770486

### 匯出資料

In [ ]:
fxhash_data.to_csv(f"{file_name}.csv", encoding="utf-8")